[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./"}]

solc = "0.8.28"
evm_version = "cancun"

optimizer = true
optimizer_runs = 2000000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
func_attrs_with_params_multiline = false

[profile.default.fuzz]
runs = 1024

[profile.default.invariant]
runs = 512
depth = 64
# fail_on_revert default is false
